version: '3.8'

services:
  agent:
    build: .
    ports:
      - "7778:7778"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - FREEPIK_API_KEY=${FREEPIK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
