version: '3.8'

services:
  agent:
    build: .
    ports:
      - "7778:7778"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - FREEPIK_API_KEY=${FREEPIK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
    restart: unless-stopped
